/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出
         * @description 先取 id_token 作 hint 再删本地会话，清 aiplatform_session cookie 并 302 到
         *     identity RP-Initiated Logout（清 identity 侧 SSO 会话），identity 按
         *     post_logout_redirect_uri 白名单 302 回前端首页。前端以 form POST 姿态调用。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 创建工作区
         * @description 记录落库（provisioning 态）即返回：单容器沙箱（all-in-one：应用与 pg/redis 同容器，
         *     /workspace 唯一持久卷）转后台置备（成功回填端口 + 资源转 ready，失败转
         *     failed）。kind 缺省 1（DEV）；Phase A 仅支持 DEV，其余 kind 返回 WSP_007。资源 url
         *     即 .env 注入的容器内回环连接串，置备完成前清单为空、端口为 0。
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重试置备
         * @description 置备失败（failed）转置备中（provisioning）并重新提交后台置备，成功回填端口 +
         *     资源转 ready；非 failed 态返回 WSP_009。
         */
        post: operations["retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 工作区内执行命令
         * @description dev 容器内 sh -c 执行，返回 stdout/stderr/exitCode；非 0 退出码是命令失败，不是环境故障。
         */
        post: operations["exec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目列表（状态过滤）
         * @description 创建时间倒序。status 过滤（Integer code）：1=ACTIVE（进行中）/3=ARCHIVED（已归档）；缺省 all。不合法取值 400 PRJ_014
         */
        get: operations["list"];
        put?: never;
        /**
         * 建项目（一句话创建：建即自动跑 BA 需求梳理）
         * @description 创建精简：只传 requirement（可空 = 缺省开场提示）。项目名由 LLM 异步生成——响应即返（名称 = 占位「未命名项目」），取名后台完成后详情/列表自然见新名（禁截取派生，失败保占位经改名端点可改）；类型单模板服务端缺省。单容器沙箱就绪（应用与 pg/redis 同容器，数据落工作区卷）。响应携带自动 BA 运行 runId（挂 /api/agent-events?runId= 的锚）。SSE：workspace-created → agent 流事件
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 改名（需求端右栏「项目信息」inline 改名）
         * @description 名称后改的显式动作（占位名/生成名/已具名均可改，含已归档项目）。响应与详情端点同构——前端改名成功后 invalidate projects 域刷新列表/顶栏。空白拒绝 400 PRJ_005（与建项目同口径），长度上限 100 超限 400；单账号场景不设越权面、不发射 SSE（REST 响应即触达）
         */
        post: operations["rename"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/questions/{qid}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 问答卡作答（ask_user 挂起续跑）
         * @description qid = 挂起帧 engineRef（续跑批复的锚）。请求体回传挂起轮 runId 与待确认工具清单（wait-raised 帧 data.toolCalls 原样）+ 用户答复文本（单选 label / 多选拼接 / 自由输入，可与已勾选合并）。续跑续在同一 run 上收口，过程帧经 SSE；恢复私货（会话/角色卡/工作区）从项目侧事实重建。空白答复 400；已归档 409 PRJ_013；项目不存在 404 PRJ_001
         */
        post: operations["answerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 指令区发言（BA 访谈后续轮）
         * @description content 即用户在指令区输入的这句话——BA 续同一 ba-{projectId} 会话消化（催促收敛、PRD 修订意见同从此进；首次生成后对系统的意见也从这里进——BA 判定后经 startFixRun 派修正 run，判定内化无需标注类型）。异步提交即返回，runId = 本轮 BA 运行标识（挂 /api/agent-events?runId= 的锚），回复与下一问经 SSE 到达。空白 400；已归档 409 PRJ_013（指令区关闭）；项目不存在 404 PRJ_001
         */
        post: operations["postMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 开始做系统（触发首次生成）
         * @description 纯动作无门——PRD 已产出即可发起（待定项未清也可）。平台先把工作区布局资产就位（AGENTS.md 平台约定幂等覆写），随后下发编码智能体（coder-{projectId} 会话，AgentScope 单栈，读 docs/PRD.md 在沙箱实现系统并起 8081 端口服务）。异步提交即返回，runId = 首试运行标识（挂 /api/agent-events?runId= 的锚），过程帧经 SSE（role-assigned role=CODER）。失败自动重试有限次（app.generation.max-attempts，默认 3 次含首试）：重试帧 task-retrying（话术「遇到问题，正在重试」），超限转终态失败、由用户重新发起兜底。run 成功收口落 generated_at（首次生成时点，单向置位）。已归档 409 PRJ_013；已生成或生成在途 409 PRJ_017；PRD 从未产出 409 PRJ_018（前端入口本就以 PRD 产出为呈现条件，本守卫拦直连调用）；项目不存在 404 PRJ_001
         */
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 归档（单向终点）
         * @description 落 archived_at：归档是真实动作，重复归档 409 PRJ_013。归档不清工作区
         */
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 登录发起
         * @description 种 oauth_txn 事务 cookie（state:nonce:returnTo，600s）并 302 到 identity
         *     /authorize。returnTo 只接受单个 / 开头的同源相对路径（#32，非法回落 /），
         *     登录成功后回跳该路径。
         */
        get: operations["login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 授权码回调
         * @description identity 302 落点（经前端 3333 同源代理）。state 与事务 cookie 精确比对 →
         *     换 token（含 JWKS RS256 验签 + iss/aud/exp/nonce）→ 账号 upsert → 种
         *     aiplatform_session 并 302 回 returnTo。失败 302 回 /?error=state_mismatch
         *     或 /?error=exchange_failed（identity 拒绝授权只带 error 不带 code 时同走
         *     exchange_failed；具体原因只进服务端日志）。
         */
        get: operations["callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询工作区
         * @description 记录 + 资源清单 + 置备状态/失败原因。服务重启后可查（重启接回的验证面）。
         */
        get: operations["get"];
        put?: never;
        post?: never;
        /**
         * 销毁工作区
         * @description 级联清理：容器 → 卷（pg 数据与引擎会话都在卷内）→ 库记录。
         */
        delete: operations["destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目详情
         * @description status = 派生项目状态（Integer code：1=进行中 3=已归档，归档优先）
         */
        get: operations["get_1"];
        put?: never;
        post?: never;
        /**
         * 删除项目（真删级联）
         * @description 容器/卷级联清理 + wsp_*\/prj_* 库记录删除；SSE workspace-destroyed
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目用量（总量 + 平台成本 + 分模型 + 分智能体）
         * @description 经计量查询端口按 subject=projectId 聚合。cost 为平台成本口径（token × 事件时点生效单价的机械乘法，币种分桶不折算，无加价/售价）；unpriced 标注有用量但未配单价的档位（其分量不含于 cost，不伪装 0）；byAgentKind 按 dims.agentKind 聚合
         */
        get: operations["usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/source-package": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 源码包下载（常开）
         * @description 交付物 = 源码包 + 仓内文档：打包项目 dev 工作区为 tar.gz（排除 .env 机密与 node_modules）。响应为二进制文件流（application/gzip，本端点不走 ApiResponse JSON 信封）
         */
        get: operations["sourcePackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 预览（工作区端口暴露）
         * @description 把工作区容器端口发布到主机返回可访问 URL（localhost）；端口真实暴露后SSE preview-ready。产物可访问即预期效果（未起服务时连接拒绝属真实状态）
         */
        get: operations["preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/prd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * PRD 读（当前版 markdown，直读工作区）
         * @description PRD = 项目 dev 工作区的 docs/PRD.md（事实源，BA 的 savePrd 写出，v1 无版本链只最新版）——本端点直读工作区文件返回 {projectId, content, updatedAt}，updatedAt = 文件 mtime（ISO-8601，秒精度）。未产出（工作区无该文件）404 PRJ_015，与项目不存在的 PRJ_001 区分，前端据此呈现「还没产出」。写出/更新时通知通道（/api/events?projectId=）发 document-updated（payload {projectId, documentType:"PRD"}），消费姿势 = invalidate 文档域后重拉本端点
         */
        get: operations["prd"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目文件树（交付文件只读浏览）
         * @description 交付文件视图 = 项目 dev 工作区剔除非交付物（data/、.platform/、node_modules/ 与 .env——与源码包同口径）后的文件清单：[{path, size}]，path 为工作区相对路径、按路径稳定排序，只列文件（目录由前端按路径段合成）。直读工作区实时状态——生成/修正 run 完成后即反映最新文件长出。项目不存在 404 PRJ_001
         */
        get: operations["files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 文本文件内容（文件模式点看）
         * @description path = 工作区相对路径（文件树条目原样回传）。只收文本且限大小：非交付物/机密/逃逸路径 400 PRJ_020（判定层拒绝，工作区不被触达）；文件不存在 404 PRJ_021；超过在线查看上限（1 MiB，容器侧拦截不读取）400 PRJ_022；非文本（正文含 NUL）400 PRJ_023。项目不存在 404 PRJ_001
         */
        get: operations["fileContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前登录账号
         * @description 凭 aiplatform_session 会话返回 accountId + displayName；无会话 401（统一信封）。
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订阅平台通知事件流（SSE）
         * @description 平台状态变化的广播（通道一）。事件只让 UI「活」，状态以 REST 重查为准，永不补发。
         *
         *     信封：SSE name 恒为 `event`；id = `{projectId}:{seq}`；data = `{"type","payload","ts"}`
         *     （payload 恒为对象、必带 projectId、内禁 type 键名）。心跳：每 15s 发注释行 `:ping`
         *     （不进 listener，仅保活）。订阅：`?projectId=` 过滤（缺省全量）。
         *
         *     名册（type → payload 字段）：
         *
         *     | type | payload 字段 |
         *     |---|---|
         *     | workspace-created | projectId, projectName, container, projectType |
         *     | preview-ready | projectId, url |
         *     | workspace-destroyed | projectId |
         *     | document-updated | projectId, documentType |
         *     | project-renamed | projectId, projectName |
         *
         *     名册正本与字段细则：docs/spec/SSE事件清单.md（新增顶层 type 先进清单再上线）。
         */
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订阅智能体流事件流（SSE）
         * @description 一次智能体运行的增量过程流（通道二，组件级消费——看某个运行才挂）。
         *     带近期帧缓冲的热流：新连接（无 Last-Event-ID 值——缺席或空串）先补发命中订阅
         *     过滤的最近缓冲帧（默认 1000 帧，配置 app.agent-stream.replay-depth），再无缝进
         *     实时流；断线重连（浏览器自动携带非空 Last-Event-ID）不补发，前端对齐以 REST
         *     重查兜底。缓冲为单实例内存态（重启即失，多实例化时需重估）。
         *
         *     信封：SSE name 恒为 `event`；id = `{runId}:{seq}`；data = `{"type","payload","ts"}`
         *     （payload 恒为对象、必带 runId、内禁 type 键名）。心跳：每 15s 发注释行 `:ping`。
         *     订阅：`?projectId=` / `?runId=` 过滤（与 payload 关联字段同名，可叠用 AND；
         *     缺省全量）；智能体事件带 projectId（编排桥接注入）。
         *
         *     名册（type → 说明，payload 除关联字段外）：
         *
         *     | type | 类别 | payload 字段 |
         *     |---|---|---|
         *     | task-start | 平台 | runId, prompt, model, engine |
         *     | session-created | 平台 | runId, sessionId, engine |
         *     | error | 平台 | runId, message |
         *     | task-finish | 平台 | runId, sessionId, engine, finish |
         *     | wait-raised | 平台 | runId, sessionId, kind, summary, engineRef, data（问答卡投影与待确认工具清单） |
         *     | text / reasoning / patch / tool / step-start / step-finish | 引擎透传 | … + `data`（引擎 part 原样） |
         *
         *     名册正本与字段细则：docs/spec/SSE事件清单.md（新增顶层 type 先进清单再上线）。
         */
        get: operations["subscribe_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 账号清单
         * @description 全量账号（建档顺序、不分页）。accountId 为 TSID 十进制字符串
         */
        get: operations["accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateWorkspaceCommand: {
            /** @description 1=开发, 2=测试, 3=生产 */
            kind?: number;
        };
        ApiResponseWorkspaceResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["WorkspaceResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            field?: string;
            message?: string;
            errorCode?: string;
        };
        MiddlewareResourceResponse: {
            /** @description 1=PostgreSQL, 2=Redis */
            kind?: number;
            kindName?: string;
            containerName?: string;
            /** Format: int32 */
            hostPort?: number;
            url?: string;
        };
        WorkspaceResponse: {
            workspaceId?: string;
            /** @description 1=开发, 2=测试, 3=生产 */
            kind?: number;
            kindName?: string;
            containerName?: string;
            networkName?: string;
            /** Format: int32 */
            hostPort?: number;
            /** Format: int32 */
            previewPort?: number;
            /** @description 1=置备中, 2=就绪, 3=失败 */
            status?: number;
            statusName?: string;
            provisionError?: string;
            resources?: components["schemas"]["MiddlewareResourceResponse"][];
            /** Format: date-time */
            createdAt?: string;
        };
        WorkspaceExecCommand: {
            command: string;
        };
        ApiResponseExecResultResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ExecResultResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ExecResultResponse: {
            stdout?: string;
            stderr?: string;
            /** Format: int32 */
            exitCode?: number;
        };
        CreateProjectCommand: {
            requirement?: string;
        };
        ApiResponseProjectCreatedResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectCreatedResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ProjectCreatedResponse: {
            project?: components["schemas"]["ProjectDetailResponse"];
            runId?: string;
        };
        ProjectDetailResponse: {
            id?: string;
            name?: string;
            /** @description 1=官网, 2=电商 */
            type?: number;
            typeName?: string;
            workspaceId?: string;
            /** @description 1=进行中, 3=已归档 */
            status?: number;
            statusName?: string;
            archived?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            prdProducedAt?: string;
            /** Format: date-time */
            generatedAt?: string;
        };
        RenameProjectCommand: {
            /** @description 新项目名（空白拒绝 PRJ_005，长度上限 100 与建项目同口径） */
            name: string;
        };
        ApiResponseProjectDetailResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectDetailResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        AnswerQuestionCommand: {
            runId: string;
            toolCalls: components["schemas"]["ToolCall"][];
            answer: string;
        };
        ToolCall: {
            id?: string;
            name?: string;
            input?: {
                [key: string]: Record<string, never>;
            };
        };
        ApiResponseVoid: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: Record<string, never>;
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        PostMessageCommand: {
            content: string;
        };
        ApiResponseInterviewTurnResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["InterviewTurnResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        InterviewTurnResponse: {
            runId?: string;
        };
        ApiResponseGenerationStartResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["GenerationStartResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        GenerationStartResponse: {
            runId?: string;
        };
        ApiResponseListProjectResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ProjectResponse: {
            id?: string;
            name?: string;
            /** @description 1=官网, 2=电商 */
            type?: number;
            typeName?: string;
            workspaceId?: string;
            /** @description 1=进行中, 3=已归档 */
            status?: number;
            statusName?: string;
            archived?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AgentKindUsage: {
            agentKind?: string;
            agentKindLabel?: string;
            tokens?: components["schemas"]["TokenUsage"];
        };
        ApiResponseProjectUsageResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectUsageResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ModelUsage: {
            provider?: string;
            model?: string;
            tokens?: components["schemas"]["TokenUsage"];
        };
        ProjectUsageResponse: {
            projectId?: string;
            total?: components["schemas"]["TokenUsage"];
            cost?: {
                [key: string]: number;
            };
            unpriced?: components["schemas"]["UnpricedUsage"][];
            byModel?: components["schemas"]["ModelUsage"][];
            byAgentKind?: components["schemas"]["AgentKindUsage"][];
        };
        TokenUsage: {
            /** Format: int64 */
            input?: number;
            /** Format: int64 */
            output?: number;
            /** Format: int64 */
            cacheRead?: number;
            /** Format: int64 */
            cacheWrite?: number;
            /** Format: int64 */
            reasoning?: number;
        };
        UnpricedUsage: {
            provider?: string;
            model?: string;
            /** @description 1=输入, 2=输出, 3=缓存读, 4=缓存写, 5=推理 */
            tokenKind?: number;
            tokenKindName?: string;
        };
        ApiResponseProjectPreviewResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectPreviewResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ProjectPreviewResponse: {
            url?: string;
        };
        ApiResponsePrdResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PrdResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        PrdResponse: {
            projectId?: string;
            content?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseProjectFilesResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectFilesResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        FileEntry: {
            path?: string;
            /** Format: int64 */
            size?: number;
        };
        ProjectFilesResponse: {
            projectId?: string;
            files?: components["schemas"]["FileEntry"][];
        };
        ApiResponseProjectFileContentResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectFileContentResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ProjectFileContentResponse: {
            path?: string;
            content?: string;
        };
        ApiResponseMeResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MeResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        /** @description 当前登录账号 */
        MeResponse: {
            /**
             * @description 账号 id（内部 TSID，字符串承载——超出 JS 安全整数范围）
             * @example 3897654321098765432
             */
            accountId?: string;
            /**
             * @description 显示名（nickname→name→preferred_username→sub 推导）
             * @example 张三
             */
            displayName?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        AccountResponse: {
            accountId?: string;
            displayName?: string;
        };
        ApiResponseListAccountResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AccountResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                aiplatform_session?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWorkspaceResponse"];
                };
            };
        };
    };
    retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWorkspaceResponse"];
                };
            };
        };
    };
    exec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceExecCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExecResultResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                status?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListProjectResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectCreatedResponse"];
                };
            };
        };
    };
    rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameProjectCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    answerQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                qid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerQuestionCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    postMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostMessageCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInterviewTurnResponse"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGenerationStartResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: {
                /** @description 登录后回跳路径（同源相对路径，非法回落 /） */
                returnTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    callback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                oauth_txn?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id（TSID 字符串） */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWorkspaceResponse"];
                };
            };
        };
    };
    destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    usage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectUsageResponse"];
                };
            };
        };
    };
    sourcePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectPreviewResponse"];
                };
            };
        };
    };
    prd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePrdResponse"];
                };
            };
        };
    };
    files: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectFilesResponse"];
                };
            };
        };
    };
    fileContent: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectFileContentResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMeResponse"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: {
                /** @description 按项目过滤（与信封关联字段同名；缺省 = 全量） */
                projectId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    subscribe_1: {
        parameters: {
            query?: {
                /** @description 按项目过滤（业务桥接注入的字段；缺省不过滤） */
                projectId?: string;
                /** @description 按运行过滤（「看某个运行才挂」的常规姿势） */
                runId?: string;
            };
            header?: {
                /** @description SSE 断线重连自动携带；无值（缺席或空串）= 新连接 = 先补发最近缓冲帧，有值 = 重连 = 不补发（REST 重查兜底） */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    accounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAccountResponse"];
                };
            };
        };
    };
}
