/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/engine-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前生效引擎（后台）
         * @description 平台当前生效的开发智能体引擎名。从未配置时返回注册表缺省 opencode，
         *     不报错。可切换的合法值全量见 `GET /api/agent-engines`（能力矩阵），
         *     本值即矩阵中的当前项。生效口径 = 新项目生效、存量不迁：切换只影响
         *     此后创建的项目，存量项目固化其创建时的引擎。
         */
        get: operations["current"];
        /**
         * 切换生效引擎（后台）
         * @description engine 必填，须 ∈ `GET /api/agent-engines` 注册表，非法值 400 AGT_009。
         *     即时生效（读库不缓存），持久化重启不丢。只影响此后创建的项目——
         *     存量项目固化其创建时的引擎跑完，任务下发走项目记录，不受切换影响。
         */
        put: operations["switchEngine"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出
         * @description 先取 id_token 作 hint 再删本地会话，清 aiplatform_session cookie 并 302 到
         *     identity RP-Initiated Logout（清 identity 侧 SSO 会话），identity 按
         *     post_logout_redirect_uri 白名单 302 回前端首页。前端以 form POST 姿态调用。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 创建工作区
         * @description 落定全部真实副作用后返回：dev 容器 + 专属 network + 独立 pg/redis（就绪等待）+
         *     /workspace/.env 连接串注入 + wsp_* 落库。kind 缺省 1（DEV）；Phase A 仅支持
         *     DEV，其余 kind 返回 WSP_007。资源 url 即 .env 注入的容器网络内连接串（含凭据）。
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 工作区内执行命令
         * @description dev 容器内 sh -c 执行，返回 stdout/stderr/exitCode；非 0 退出码是命令失败，不是环境故障。
         */
        post: operations["exec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/agent/waits/{waitId}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 答复等待点
         * @description 三型：`{"type":"answer","answers":[["Vue3"]]}`（问答）/ `{"type":"permission",
         *     "approve":false}`（权限）/ `{"type":"deferred","note":"转任务"}`（转任务关闭）。
         *     校验：非 PENDING 或会话不可续跑 → 409；等待点不存在 → 404；引擎不可达 → 502
         *     （保持 PENDING 可重试）。同 run 权限拒绝累计达上限（默认 3，可配）触发平台
         *     终止运行。
         */
        post: operations["settle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/agent/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 下发任务
         * @description runId 平台生成并随响应返回（该运行全部 agent 流事件携带）。异步：立即返回，
         *     过程事件经 `GET /api/agent-events` 透传。systemPrompt/modelId 是入参（适配层
         *     零角色概念）；sessionId 非空 = 复用既有会话续跑；engine 缺省 = 后台全局
         *     配置的生效引擎（`GET /api/admin/engine-config`，未配置时 opencode；
         *     可选值见 `GET /api/agent-engines`）。
         */
        post: operations["dispatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/agent/sessions/{sessionId}/questions/{requestId}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 回答问题
         * @description answers 按问题顺序，每项 = 该问题选中的标签列表（custom 输入也作为标签）；agent 收到答复继续跑。
         */
        post: operations["replyQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/agent/sessions/{sessionId}/permissions/{permissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 权限审批
         * @description approve=true 批准（once）/ false 拒绝（reject）。无权限通道的引擎（dsh）为 no-op。
         */
        post: operations["replyPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交任务（执行中 → 已提交）
         * @description 仅指派本人。载荷两种形状二选一（A4 §3）：首轮 {report, bugs:[{title, description, reproSteps, severity}]}（空清单允许——测试全过）；复测 {report, results:[{bugId, pass, note}]}（bugId 须为本项目 Bug，404 TASK_005）。形状不合法 400 TASK_006。载荷暂存 submitted_payload，Bug 确认时才入库（驳回路径天然干净）。SSE：task-updated(status=SUBMITTED)
         */
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 开始任务（已发布 → 执行中）
         * @description 仅指派本人（403 TASK_004）；已开始/终态 409 TASK_002。SSE：task-updated(status=IN_PROGRESS)
         */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 驳回任务（已提交 → 执行中退回，dev）
         * @description reason 必填（400 TASK_003）；任务回到执行中、驳回理由/时间落库（OPC TASK_REJECTED 待办亮起）。SSE：task-updated(status=IN_PROGRESS)
         */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 确认任务（已提交 → 已确认，dev）
         * @description 一事务内：首轮 → Bug 清单批量落库（OPEN，空清单即无入库、G3 直接就绪）；复测 → 逐条翻态（pass=true → VERIFIED 唯一关闭态 / false → 退回 OPEN，修复再派发随 #27）；并发 TaskCompleted 应用事件（AFTER_COMMIT——转任务回填续跑的锚，#27 消费）。幂等以状态机守门：重复确认 409 TASK_002。SSE：task-updated(status=CONFIRMED)
         */
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消任务（已发布/执行中 → 已取消，dev）
         * @description 已提交不能取消只能驳回（409 TASK_002）；终态不可再动。SSE：task-updated(status=CANCELLED)
         */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目列表（状态过滤）
         * @description 创建时间倒序。status 过滤（Integer code）：1=ACTIVE（开发中）/ 2=PENDING（存在 dev 待办：门就绪或等待点待处理）/ 3=ARCHIVED（已归档）；缺省 all。不合法取值 400 PRJ_014
         */
        get: operations["list"];
        put?: never;
        /**
         * 建项目（一句话创建：建即自动跑 BA 需求梳理）
         * @description #39 创建精简：只传 requirement（可空 = 缺省开场提示）。项目名由 LLM 异步生成——响应即返（名称 = 占位「未命名项目」），取名后台完成后详情/列表自然见新名（禁截取派生，失败保占位经改名端点可改）；类型单模板服务端缺省；引擎 = 后台全局配置的生效引擎（/api/admin/engine-config，未配置时 opencode）创建时固化。dev 工作区 + 专属 pg/redis 就绪 → 第 1 期（BA 段 OPEN）。响应携带自动 BA 运行 runId（挂 /api/agent-events?runId= 的锚）。SSE：workspace-created → stage-changed(BA) → agent 流事件
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/agent/waits/{waitId}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 答复等待点（问答答复 / 权限批准或拒绝 / 转任务）
         * @description type=answer（answers=选项 label 二维）/ permission（approve）/ deferred（转任务：task={title, content?, assigneeAccountId} 必填——关等待点 + 建任务存 waitId 引用，任务确认后自动复用原会话续跑（prompt=测试报告摘要））。agent 收到答复续跑；权限拒绝累计达上限由平台终止（不形成审批循环）；成功后 SSE wait-settled（outcome=answered/approved/denied/deferred）
         */
        post: operations["settle_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/agent/task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 下任务（手动 DEV/ARCH 或任意角色卡）
         * @description 角色缺省取当前阶段默认角色（无默认角色的阶段需显式指定，409 PRJ_004）。runId 随响应返回，SSE 帧序：role-assigned → task-start → session-created → 过程流 → task-finish。run 被接受即计入当前阶段任务计数（门禁输入）
         */
        post: operations["dispatchTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目任务列表（全量，新→旧）
         * @description 含状态/驳回理由/提交载荷（确认与驳回的裁决输入）；status：1=已发布 2=执行中 3=已提交 4=已确认 5=已取消
         */
        get: operations["list_1"];
        put?: never;
        /**
         * 建测试任务（指派 OPC 账号）
         * @description type 固定 TEST（v1 单值）；assignee 必填（指派与领取分离，v1 只指派——账号清单 GET /api/accounts）。期在开发段时本动作是开发→测试的唯一触发（advance + stage-changed；复测/期后不动）。指派账号不存在 404 TASK_008。SSE：task-updated(status=PUBLISHED)。转任务来源（waitId）是程序化入参，REST 面不收（#27 回填）
         */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/stage/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 门驳回（一律停留当前阶段；G1/G2 驳回自动回流）
         * @description reason 必填（驳回反馈是前端展示与纪要来源）。驳回不迁移阶段——验收驳回停留验收段，开发平台照常下修复任务，用户再验收（A3 §3）；留痕落 prj_confirmations（decision=驳回）。驳回回流（#50/#46）：需求确认（G1）驳回自动回流 BA 续访谈；Demo 确认（G2）驳回自动起 DEMO 修正 run（意见注入续 Demo 会话，预览后用户再确认）。requirementChange=true（G2 表单显式标记，缺省 false）时意见同时回流 BA 修订 PRD（document-updated 可观测，Demo 修正以新 PRD 为准）；不带标记不触发任何 BA 活动。SSE：stage-changed(rejected=true, reason)
         */
        post: operations["reject_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/stage/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 门通过（推进；验收门通过即收口）
         * @description 无体——拍板即全部事实（approve 也留痕 prj_confirmations，含 accountId）。门禁 = 引擎计数（每门 taskCount≥1，验收门=0）∧ 业务谓词（需求确认 = PRD 已产出，开发完成确认 = 无未关闭 Bug），不足 409 PRJ_007/PRJ_008/PRJ_016；无门段 409 PRJ_009；无 OPEN 期 409 PRJ_010。需求确认（G1）通过自动跑 Demo；验收（G4）通过即收口：期 CLOSED、项目已交付。SSE：stage-changed(approved=true)
         */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 改名（需求端右栏「项目信息」inline 改名）
         * @description #43：名称后改的显式动作（占位名/生成名/已具名均可改，含已归档项目）。响应与详情端点同构——前端改名成功后 invalidate projects 域刷新列表/顶栏。空白拒绝 400 PRJ_005（与建项目同口径），长度上限 100 超限 400；单账号场景不设越权面、不发射 SSE（REST 响应即触达）
         */
        post: operations["rename"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/demand-pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 需求池清单（新→旧）
         * @description 项目的收件清单时间线，记录时间倒序
         */
        get: operations["demandEntries"];
        put?: never;
        /**
         * 需求池入池（随时可记）
         * @description 项目级收件清单（A3 §4）：验收前后、期开期关都能记；kind 可空（收件时不强分类），source 缺省用户；入池是显式动作（驳回反馈不自动入池）。开新期时作为需求梳理输入
         */
        post: operations["addDemandEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/bugs/{bugId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * bogus Bug 手工关闭（reason 必填）
         * @description OPEN/FIXED → VERIFIED + closed_reason——复测通过唯一关闭态的带理由别名动作，不加第四态（G3 谓词不变）；VERIFIED 终态再关 409 TASK_002。跨项目/不存在 404 TASK_005
         */
        post: operations["close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/bugs/dispatch-fixes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修复（重）派发（幂等手动）
         * @description 只派 OPEN ∧ 无修复 run 引用的 Bug；已有修复 run 在飞则空转（同项目同时至多一个修复 run，逐 Bug 一 run 一新会话串行链）。确认时点自动触发（首轮入库/复测退回），本端点是手动兜底——失败回池的 Bug 由下次派发重试
         */
        post: operations["dispatchFixes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 归档（单向终点）
         * @description 落 archived_at（A3 §4）：区别于开发中/已交付的派生投影——归档是真实动作，重复归档 409 PRJ_013。归档不迁移期、不清工作区（工具项目级常开）
         */
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 登录发起
         * @description 种 oauth_txn 事务 cookie（state:nonce:returnTo，600s）并 302 到 identity
         *     /authorize。returnTo 只接受单个 / 开头的同源相对路径（#32，非法回落 /），
         *     登录成功后回跳该路径。
         */
        get: operations["login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 授权码回调
         * @description identity 302 落点（经前端 3333 同源代理）。state 与事务 cookie 精确比对 →
         *     换 token（含 JWKS RS256 验签 + iss/aud/exp/nonce）→ 账号 upsert → 种
         *     aiplatform_session 并 302 回 returnTo。失败 302 回 /?error=state_mismatch
         *     或 /?error=exchange_failed（identity 拒绝授权只带 error 不带 code 时同走
         *     exchange_failed；具体原因只进服务端日志）。
         */
        get: operations["callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询工作区
         * @description 记录 + 资源清单。服务重启后可查（重启接回的验证面）。
         */
        get: operations["get"];
        put?: never;
        post?: never;
        /**
         * 销毁工作区
         * @description 级联清理：容器（dev/pg/redis）→ network → 卷 → 库记录。
         */
        delete: operations["destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/agent/waits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 工作区待处理等待点
         * @description 跨会话聚合（新者在前），只有 PENDING。kind=QUESTION/PERMISSION 两类统一
         *     承载；body 为引擎载荷原样（底座不解释），summary 为适配器提取的中性短文本。
         */
        get: operations["pendingWaits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/agent/waits/{waitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 等待点单查
         * @description waitId 全局寻址（含终态行——转任务/回填的引用读面）；不存在 404。
         */
        get: operations["wait"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/agent/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 工作区会话列表
         * @description 按 workspaceId 寻址、跨重启存活（服务重启后照常可查，续跑缝的寻址面）。
         */
        get: operations["sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/agent/sessions/{sessionId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 会话内待答问题
         * @description 引擎载荷原样（底座不解释：question/header/options/...）。无问答能力的引擎
         *     （dsh）恒空——能力矩阵见 `GET /api/agent-engines`。
         */
        get: operations["questions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/agent/engines/{engine}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 引擎健康
         * @description opencode = 容器内 serve 可达（不拉起，只探活）；dsh = CLI 可用。
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 待办列表
         * @description view=dev|opc（缺省 dev）的计算式投影：AGENT_WAIT（refId=waitId）/ GATE_PENDING（refId=projectId），任务型随 A4；不分页，新者在前。
         */
        get: operations["todos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指派给我的任务（opc 跨项目，新→旧）
         * @description assignee=me 资源归属过滤（A4 §7）；卡片带最小项目上下文（project.name + project.previewUrl——OPC 测试要看预览）与驳回理由
         */
        get: operations["myTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 任务详情（opc/dev 共用）
         * @description opc 校验 assignee=me（项目 owner 视为 dev 侧放行，403 TASK_004）；带项目 Bug 清单（复测表单 bugId 源 / dev 确认复审对照）与提交载荷对象形态（首轮 {report, bugs[]} / 复测 {report, results[]}）
         */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/agent/waits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目的待处理等待点
         * @description 跨会话聚合 PENDING（新→旧）：问答（kind=QUESTION）与权限（kind=PERMISSION）；body 为引擎载荷原样（问题选项等）
         */
        get: operations["pendingWaits_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目详情（期位置 + 主链定义数据 + 门就绪 + 派生状态）
         * @description 前端渲染进度条与点亮按钮的全部数据面（A3 §5）：stages = 阶段序列（主链定义数据，过程演化 UI 少改）；gate = {actor, ready}（计数门禁 ∧业务谓词，无门段/已收口为 null）；status = 派生项目状态（Integer code：1=开发中 2=已交付 3=已归档，有无 OPEN 期的投影，归档优先）
         */
        get: operations["get_1"];
        put?: never;
        post?: never;
        /**
         * 删除项目（真删级联）
         * @description 容器/网络/卷级联清理 + wsp_*\/prj_* 库记录删除；SSE workspace-destroyed
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目用量（总量 + 平台成本 + 分模型 + 分角色 + 按期）
         * @description 经计量查询端口按 subject=projectId 聚合（A1 §2.5 + A6 §3）。cost 为平台成本口径（token × 事件时点生效单价的机械乘法，币种分桶不折算，无加价/售价）；unpriced 标注有用量但未配单价的档位（其分量不含于 cost，不伪装 0）；byIteration 按 dims.iterationId 聚合（run 发起时快照）——期后修复 run 不带该维度，入项目总量不入任何期桶（收口期成本定格）
         */
        get: operations["usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/source-package": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 源码包下载（常开）
         * @description 交付物 = 源码包 + 仓内文档（A3 §2.2）：打包项目 dev 工作区为 tar.gz（排除 .env 机密与 node_modules）。响应为二进制文件流（application/gzip，本端点不走 ApiResponse JSON 信封）
         */
        get: operations["sourcePackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 预览（工作区端口暴露）
         * @description 把工作区容器端口发布到主机返回可访问 URL（localhost）；端口真实暴露后SSE preview-ready。Demo 段产物可访问即预期效果（未起服务时连接拒绝属真实状态）
         */
        get: operations["preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/prd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * PRD 读（当前版 markdown，直读工作区）
         * @description PRD = 项目 dev 工作区的 docs/PRD.md（事实源，BA 的 savePrd 写出，v1 无版本链只最新版）——本端点直读工作区文件返回 {projectId, content, updatedAt}，updatedAt = 文件 mtime（ISO-8601，秒精度）。未产出（工作区无该文件）404 PRJ_015，与项目不存在的 PRJ_001 区分，前端据此呈现「还没产出」。写出/更新时通知通道（/api/events?projectId=）发 document-updated（payload {projectId, documentType:"PRD"}），消费姿势 = invalidate 文档域后重拉本端点
         */
        get: operations["prd"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/bugs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目 Bug 清单（新→旧）
         * @description status：1=OPEN 待修复 2=FIXED 已修复 3=VERIFIED 复测通过（唯一关闭态；G3 谓词 open = status ≠ 3）。fix_run_id/fix_note 随修复链写入（in-flight = OPEN ∧ fix_run_id 非空），closed_reason 随手工关闭
         */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前登录账号
         * @description 凭 aiplatform_session 会话返回 accountId + displayName；无会话 401（统一信封）。
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 知识语义检索
         * @description 全局跨项目纯相似 topK（不过滤、不配额，A5 §3）。kind = 素材类别（ARTIFACT/QA/FEEDBACK/TEST_REPORT/BUG）；projectName 为来源项目（跨项目命中是特性）。q 空白 400 KNW_002、topK 非正 400 KNW_003；embedding 服务不可用时返回空列表（降级不炸）
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订阅平台通知事件流（SSE）
         * @description 平台状态变化的广播（通道一）。事件只让 UI「活」，状态以 REST 重查为准，永不补发。
         *
         *     信封：SSE name 恒为 `event`；id = `{projectId}:{seq}`；data = `{"type","payload","ts"}`
         *     （payload 恒为对象、必带 projectId、内禁 type 键名）。心跳：每 15s 发注释行 `:ping`
         *     （不进 listener，仅保活）。订阅：`?projectId=` 过滤（缺省全量）。
         *
         *     名册（type → payload 字段）：
         *
         *     | type | payload 字段 |
         *     |---|---|
         *     | workspace-created | projectId, projectName, container, projectType, engine |
         *     | stage-changed | projectId, stage, stageLabel, approved?, rejected?, reason? |
         *     | preview-ready | projectId, url |
         *     | workspace-destroyed | projectId |
         *     | task-updated | projectId, taskId, status |
         *
         *     名册正本与字段细则：docs/spec/SSE事件清单.md（新增顶层 type 先进清单再上线）。
         */
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订阅 agent 流事件流（SSE）
         * @description 一次智能体运行的增量过程流（通道二，任务进度页组件级消费——看某个运行才挂）。
         *     Phase A 不补发，断线重连后前端对齐以 REST 重查兜底。
         *
         *     信封：SSE name 恒为 `event`；id = `{runId}:{seq}`；data = `{"type","payload","ts"}`
         *     （payload 恒为对象、必带 runId、内禁 type 键名）。心跳：每 15s 发注释行 `:ping`。
         *     订阅：`?projectId=` / `?runId=` / `?workspaceId=` 过滤（与 payload 关联字段同名，
         *     可叠用 AND；缺省全量）；底座任务端点（POST /api/workspaces/{id}/agent/tasks）
         *     直发的事件带 workspaceId，projectId 自片5 业务编排桥接注入。
         *
         *     名册（type → 说明，payload 除关联字段外）：
         *
         *     | type | 类别 | payload 字段 |
         *     |---|---|---|
         *     | task-start | 平台 | runId, prompt, model, engine |
         *     | session-created | 平台 | runId, sessionId, engine |
         *     | error | 平台 | runId, message |
         *     | task-finish | 平台 | runId, sessionId, engine, finish |
         *     | text / reasoning / patch / tool / step-start / step-finish | 引擎透传 | … + `data`（引擎 part 原样） |
         *
         *     名册正本与字段细则：docs/spec/SSE事件清单.md（新增顶层 type 先进清单再上线）。
         */
        get: operations["subscribe_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 引擎能力矩阵
         * @description 显式注册表全量（换引擎 = 实现端口 + 注册表登记，前端自动出现新选项）：
         *     name/label/questionSupported/permissionSupported/note。任务下发 engine 参数
         *     取 name；缺省 = 后台全局配置的生效引擎（`GET /api/admin/engine-config`，
         *     未配置时 opencode）。
         */
        get: operations["matrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 账号清单（指派下拉）
         * @description 全量账号（建档顺序、不分页）：建测试任务的 assignee 下拉源。accountId 为 TSID 十进制字符串
         */
        get: operations["accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SwitchEngineCommand: {
            engine: string;
        };
        ApiResponseEngineConfigResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["EngineConfigResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        EngineConfigResponse: {
            engine?: string;
        };
        FieldError: {
            field?: string;
            message?: string;
            errorCode?: string;
        };
        CreateWorkspaceCommand: {
            /** @description 1=开发, 2=测试, 3=生产 */
            kind?: number;
        };
        ApiResponseWorkspaceResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["WorkspaceResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        MiddlewareResourceResponse: {
            /** @description 1=PostgreSQL, 2=Redis */
            kind?: number;
            kindName?: string;
            containerName?: string;
            /** Format: int32 */
            hostPort?: number;
            url?: string;
        };
        WorkspaceResponse: {
            workspaceId?: string;
            /** @description 1=开发, 2=测试, 3=生产 */
            kind?: number;
            kindName?: string;
            containerName?: string;
            networkName?: string;
            /** Format: int32 */
            hostPort?: number;
            /** Format: int32 */
            previewPort?: number;
            resources?: components["schemas"]["MiddlewareResourceResponse"][];
            /** Format: date-time */
            createdAt?: string;
        };
        WorkspaceExecCommand: {
            command: string;
        };
        ApiResponseExecResultResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ExecResultResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ExecResultResponse: {
            stdout?: string;
            stderr?: string;
            /** Format: int32 */
            exitCode?: number;
        };
        WaitSettleCommand: {
            type: string;
            answers?: string[][];
            approve?: boolean;
            note?: string;
        };
        ApiResponseVoid: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: Record<string, never>;
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        AgentTaskDispatchCommand: {
            prompt: string;
            systemPrompt?: string;
            modelId?: string;
            engine?: string;
            sessionId?: string;
        };
        AgentTaskResponse: {
            runId?: string;
            sessionId?: string;
            engine?: string;
            accepted?: boolean;
        };
        ApiResponseAgentTaskResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AgentTaskResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        AgentQuestionReplyCommand: {
            answers: string[][];
        };
        AgentPermissionCommand: {
            approve: boolean;
        };
        BugPayload: {
            title: string;
            description?: string;
            reproSteps?: string;
            /** @description 1=致命, 2=严重, 3=一般, 4=轻微 */
            severity: number;
        };
        RetestResultPayload: {
            /** Format: int64 */
            bugId: number;
            pass?: boolean;
            note?: string;
        };
        SubmitTaskCommand: {
            report: string;
            bugs?: components["schemas"]["BugPayload"][];
            results?: components["schemas"]["RetestResultPayload"][];
        };
        ApiResponseTaskResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["TaskResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        TaskResponse: {
            taskId?: string;
            projectId?: string;
            /** @description 1=测试任务 */
            type?: number;
            typeName?: string;
            title?: string;
            content?: string;
            /** Format: int64 */
            assigneeAccountId?: number;
            assigneeName?: string;
            /** @description 1=已发布, 2=执行中, 3=已提交, 4=已确认, 5=已取消 */
            status?: number;
            statusName?: string;
            waitId?: string;
            submittedPayload?: {
                [key: string]: Record<string, never>;
            };
            rejectReason?: string;
            /** Format: date-time */
            rejectedAt?: string;
            /** Format: date-time */
            confirmedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RejectTaskCommand: {
            reason: string;
        };
        ApiResponseTaskDetailResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["TaskDetailResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        BugResponse: {
            bugId?: string;
            projectId?: string;
            sourceTaskId?: string;
            title?: string;
            description?: string;
            reproSteps?: string;
            /** @description 1=致命, 2=严重, 3=一般, 4=轻微 */
            severity?: number;
            severityName?: string;
            /** @description 1=待修复, 2=已修复, 3=复测通过 */
            status?: number;
            statusName?: string;
            fixRunId?: string;
            fixNote?: string;
            closedReason?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ProjectBrief: {
            name?: string;
            previewUrl?: string;
        };
        TaskDetailResponse: {
            task?: components["schemas"]["TaskResponse"];
            project?: components["schemas"]["ProjectBrief"];
            bugs?: components["schemas"]["BugResponse"][];
        };
        CreateProjectCommand: {
            requirement?: string;
        };
        ApiResponseProjectCreatedResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectCreatedResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        GateView: {
            actor?: string;
            ready?: boolean;
        };
        ProjectCreatedResponse: {
            project?: components["schemas"]["ProjectDetailResponse"];
            runId?: string;
            accepted?: boolean;
        };
        ProjectDetailResponse: {
            id?: string;
            name?: string;
            /** @description 1=官网, 2=电商 */
            type?: number;
            typeName?: string;
            engine?: string;
            workspaceId?: string;
            stage?: string;
            stageLabel?: string;
            /** @description 1=开发中, 2=已交付, 3=已归档 */
            status?: number;
            statusName?: string;
            /** Format: int32 */
            stageTaskCount?: number;
            archived?: boolean;
            /** Format: date-time */
            createdAt?: string;
            stages?: components["schemas"]["StageView"][];
            gate?: components["schemas"]["GateView"];
        };
        StageView: {
            name?: string;
            label?: string;
            defaultRole?: string;
            gateActor?: string;
            terminal?: boolean;
        };
        DeferredTaskPayload: {
            title: string;
            content?: string;
            /** Format: int64 */
            assigneeAccountId: number;
        };
        ProjectWaitSettleCommand: {
            type: string;
            answers?: string[][];
            approve?: boolean;
            note?: string;
            task?: components["schemas"]["DeferredTaskPayload"];
        };
        ProjectAgentTaskCommand: {
            prompt: string;
            /** @description 角色卡 code：1=BA 2=DEV 3=DELIVERY 4=ARCH 5=TEST 6=DEMO；缺省取阶段默认（1=需求分析师, 2=开发工程师, 3=交付工程师, 4=架构师, 5=测试工程师, 6=原型开发工程师） */
            role?: number;
        };
        ApiResponseProjectAgentTaskResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectAgentTaskResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ProjectAgentTaskResponse: {
            runId?: string;
            sessionId?: string;
            engine?: string;
            /** @description 1=需求分析师, 2=开发工程师, 3=交付工程师, 4=架构师, 5=测试工程师, 6=原型开发工程师 */
            role?: number;
            roleName?: string;
            stage?: string;
            accepted?: boolean;
        };
        CreateTaskCommand: {
            title: string;
            content: string;
            /** Format: int64 */
            assigneeAccountId: number;
        };
        StageRejectCommand: {
            reason: string;
            /**
             * @description 涉及需求变更标记（Demo 确认门驳回表单）：true 时驳回意见同时回流 BA 触发 PRD 修订（document-updated 可观测），Demo 修正以新 PRD 为准；缺省 false——纯 Demo 意见不惊动 BA。显式标记，不做语义自动判定
             * @default false
             */
            requirementChange: boolean;
        };
        ApiResponseProjectDetailResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectDetailResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        RenameProjectCommand: {
            /** @description 新项目名（空白拒绝 PRJ_005，长度上限 100 与建项目同口径） */
            name: string;
        };
        AddDemandEntryCommand: {
            content: string;
            /** @description 1=需求, 2=缺陷 */
            kind?: number;
            /** @description 1=用户, 2=测试, 3=验收 */
            source?: number;
        };
        ApiResponseDemandPoolEntryResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["DemandPoolEntryResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        DemandPoolEntryResponse: {
            id?: string;
            content?: string;
            /** @description 1=需求, 2=缺陷 */
            kind?: number;
            kindName?: string;
            /** @description 1=用户, 2=测试, 3=验收 */
            source?: number;
            sourceName?: string;
            /** Format: int64 */
            createdBy?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        CloseBugCommand: {
            reason: string;
        };
        ApiResponseBugResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["BugResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ApiResponseListWaitPointResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["WaitPointResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        WaitPointResponse: {
            waitId?: string;
            workspaceId?: string;
            sessionId?: string;
            runId?: string;
            engineRef?: string;
            /** @description 1=问答, 2=权限 */
            kind?: number;
            kindName?: string;
            /** @description 1=待处理, 2=已答复, 3=已失效, 4=已清理 */
            status?: number;
            statusName?: string;
            summary?: string;
            body?: {
                [key: string]: Record<string, never>;
            };
            /** @description 1=已回答, 2=已批准, 3=已拒绝, 4=已转任务 */
            settleOutcome?: number;
            settleOutcomeName?: string;
            /** Format: date-time */
            raisedAt?: string;
            /** Format: date-time */
            settledAt?: string;
        };
        ApiResponseWaitPointResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["WaitPointResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        AgentSessionResponse: {
            sessionId?: string;
            workspaceId?: string;
            engine?: string;
            lastRunId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseListAgentSessionResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AgentSessionResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ApiResponseListMapStringObject: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: {
                [key: string]: Record<string, never>;
            }[];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ApiResponseBoolean: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: boolean;
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ApiResponseListTodoItemResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["TodoItemResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        TodoItemResponse: {
            type?: string;
            projectId?: string;
            refId?: string;
            title?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseListTaskCardResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["TaskCardResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        TaskCardResponse: {
            taskId?: string;
            projectId?: string;
            project?: components["schemas"]["ProjectBrief"];
            title?: string;
            content?: string;
            /** @description 1=已发布, 2=执行中, 3=已提交, 4=已确认, 5=已取消 */
            status?: number;
            statusName?: string;
            rejectReason?: string;
            /** Format: date-time */
            rejectedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseListProjectResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ProjectResponse: {
            id?: string;
            name?: string;
            /** @description 1=官网, 2=电商 */
            type?: number;
            typeName?: string;
            engine?: string;
            workspaceId?: string;
            stage?: string;
            stageLabel?: string;
            /** @description 1=开发中, 2=已交付, 3=已归档 */
            status?: number;
            statusName?: string;
            /** Format: int32 */
            stageTaskCount?: number;
            archived?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseListProjectWaitResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectWaitResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ProjectWaitResponse: {
            waitId?: string;
            /** @description 1=问答, 2=权限 */
            kind?: number;
            kindName?: string;
            /** @description 1=待处理, 2=已答复, 3=已失效, 4=已清理 */
            status?: number;
            statusName?: string;
            summary?: string;
            sessionId?: string;
            runId?: string;
            engineRef?: string;
            body?: {
                [key: string]: Record<string, never>;
            };
            /** @description 1=已回答, 2=已批准, 3=已拒绝, 4=已转任务 */
            settleOutcome?: number;
            settleOutcomeName?: string;
            /** Format: date-time */
            raisedAt?: string;
            /** Format: date-time */
            settledAt?: string;
        };
        ApiResponseProjectUsageResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectUsageResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        IterationUsage: {
            iterationId?: string;
            /** Format: int32 */
            seq?: number;
            tokens?: components["schemas"]["TokenUsage"];
        };
        ModelUsage: {
            provider?: string;
            model?: string;
            tokens?: components["schemas"]["TokenUsage"];
        };
        ProjectUsageResponse: {
            projectId?: string;
            total?: components["schemas"]["TokenUsage"];
            cost?: {
                [key: string]: number;
            };
            unpriced?: components["schemas"]["UnpricedUsage"][];
            byModel?: components["schemas"]["ModelUsage"][];
            byRole?: components["schemas"]["RoleUsage"][];
            byIteration?: components["schemas"]["IterationUsage"][];
        };
        RoleUsage: {
            role?: string;
            roleLabel?: string;
            tokens?: components["schemas"]["TokenUsage"];
        };
        TokenUsage: {
            /** Format: int64 */
            input?: number;
            /** Format: int64 */
            output?: number;
            /** Format: int64 */
            cacheRead?: number;
            /** Format: int64 */
            cacheWrite?: number;
            /** Format: int64 */
            reasoning?: number;
        };
        UnpricedUsage: {
            provider?: string;
            model?: string;
            /** @description 1=输入, 2=输出, 3=缓存读, 4=缓存写, 5=推理 */
            tokenKind?: number;
            tokenKindName?: string;
        };
        ApiResponseListTaskResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["TaskResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ApiResponseProjectPreviewResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectPreviewResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ProjectPreviewResponse: {
            url?: string;
        };
        ApiResponsePrdResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PrdResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        PrdResponse: {
            projectId?: string;
            content?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseListDemandPoolEntryResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["DemandPoolEntryResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ApiResponseListBugResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["BugResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ApiResponseMeResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MeResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        /** @description 当前登录账号 */
        MeResponse: {
            /**
             * @description 账号 id（内部 TSID，字符串承载——超出 JS 安全整数范围）
             * @example 3897654321098765432
             */
            accountId?: string;
            /**
             * @description 显示名（nickname→name→preferred_username→sub 推导）
             * @example 张三
             */
            displayName?: string;
        };
        ApiResponseListKnowledgeSearchItemResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["KnowledgeSearchItemResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        KnowledgeSearchItemResponse: {
            kind?: string;
            projectName?: string;
            title?: string;
            snippet?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        ApiResponseListEngineInfo: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["EngineInfo"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        EngineInfo: {
            name?: string;
            label?: string;
            questionSupported?: boolean;
            permissionSupported?: boolean;
            note?: string;
        };
        AccountResponse: {
            accountId?: string;
            displayName?: string;
        };
        ApiResponseListAccountResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AccountResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEngineConfigResponse"];
                };
            };
        };
    };
    switchEngine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchEngineCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEngineConfigResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                aiplatform_session?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWorkspaceResponse"];
                };
            };
        };
    };
    exec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceExecCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExecResultResponse"];
                };
            };
        };
    };
    settle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
                /** @description 等待点稳定标识 */
                waitId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitSettleCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    dispatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id（TSID 字符串） */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentTaskDispatchCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAgentTaskResponse"];
                };
            };
        };
    };
    replyQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
                /** @description 引擎会话 id */
                sessionId: string;
                /** @description 问题请求 id */
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentQuestionReplyCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    replyPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
                /** @description 引擎会话 id */
                sessionId: string;
                /** @description 权限请求 id */
                permissionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPermissionCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitTaskCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTaskResponse"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTaskResponse"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectTaskCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTaskResponse"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTaskDetailResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTaskResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                status?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListProjectResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectCreatedResponse"];
                };
            };
        };
    };
    settle_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                waitId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectWaitSettleCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    dispatchTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectAgentTaskCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectAgentTaskResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTaskResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTaskResponse"];
                };
            };
        };
    };
    reject_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageRejectCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameProjectCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    demandEntries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListDemandPoolEntryResponse"];
                };
            };
        };
    };
    addDemandEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDemandEntryCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDemandPoolEntryResponse"];
                };
            };
        };
    };
    close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                bugId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseBugCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBugResponse"];
                };
            };
        };
    };
    dispatchFixes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: {
                /** @description 登录后回跳路径（同源相对路径，非法回落 /） */
                returnTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    callback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                oauth_txn?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id（TSID 字符串） */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWorkspaceResponse"];
                };
            };
        };
    };
    destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    pendingWaits: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id（TSID 字符串） */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListWaitPointResponse"];
                };
            };
        };
    };
    wait: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
                /** @description 等待点稳定标识 */
                waitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWaitPointResponse"];
                };
            };
        };
    };
    sessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAgentSessionResponse"];
                };
            };
        };
    };
    questions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
                /** @description 引擎会话 id */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMapStringObject"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
                /** @description 引擎名（opencode / dsh） */
                engine: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBoolean"];
                };
            };
        };
    };
    todos: {
        parameters: {
            query?: {
                view?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTodoItemResponse"];
                };
            };
        };
    };
    myTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTaskCardResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTaskDetailResponse"];
                };
            };
        };
    };
    pendingWaits_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListProjectWaitResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    usage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectUsageResponse"];
                };
            };
        };
    };
    sourcePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectPreviewResponse"];
                };
            };
        };
    };
    prd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePrdResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListBugResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMeResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                topK?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListKnowledgeSearchItemResponse"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: {
                /** @description 按项目过滤（与信封关联字段同名；缺省 = 全量） */
                projectId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    subscribe_1: {
        parameters: {
            query?: {
                /** @description 按项目过滤（片5 业务桥接注入的字段；缺省不过滤） */
                projectId?: string;
                /** @description 按运行过滤（任务进度页「看某个运行才挂」的常规姿势） */
                runId?: string;
                /** @description 按工作区过滤（片2a 底座任务端点直发事件的关联字段） */
                workspaceId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    matrix: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListEngineInfo"];
                };
            };
        };
    };
    accounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAccountResponse"];
                };
            };
        };
    };
}
