/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出
         * @description 先取 id_token 作 hint 再删本地会话，清 aiplatform_session cookie 并 302 到
         *     identity RP-Initiated Logout（清 identity 侧 SSO 会话），identity 按
         *     post_logout_redirect_uri 白名单 302 回前端首页。前端以 form POST 姿态调用。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 创建工作区
         * @description 记录落库（provisioning 态）即返回：单容器沙箱（all-in-one：应用与 pg/redis 同容器，
         *     /workspace 唯一持久卷）转后台置备（成功回填端口 + 资源转 ready，失败转
         *     failed）。kind 缺省 1（DEV）；Phase A 仅支持 DEV，其余 kind 返回 WSP_007。资源 url
         *     即 .env 注入的容器内回环连接串，置备完成前清单为空、端口为 0。
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重试置备
         * @description 置备失败（failed）转置备中（provisioning）并重新提交后台置备，成功回填端口 +
         *     资源转 ready；非 failed 态返回 WSP_009。
         */
        post: operations["retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 工作区内执行命令
         * @description dev 容器内 sh -c 执行，返回 stdout/stderr/exitCode；非 0 退出码是命令失败，不是环境故障。
         */
        post: operations["exec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目列表（状态过滤）
         * @description 创建时间倒序。status 过滤（Integer code）：1=ACTIVE（进行中）/3=ARCHIVED（已归档）；缺省 all。不合法取值 400 PRJ_014
         */
        get: operations["list"];
        put?: never;
        /**
         * 建项目（一句话创建：建即自动开主智能体需求梳理）
         * @description 创建精简：只传 requirement（可空 = 缺省开场提示）。项目名由 LLM 异步生成——响应即返（名称 = 占位「未命名项目」），取名后台完成后详情/列表自然见新名（禁截取派生，失败保占位经改名端点可改）；类型单模板服务端缺省。单容器沙箱就绪（应用与 pg/redis 同容器，数据落工作区卷）。响应携带自动开场运行 runId（挂 /api/events?runId= 的锚）。SSE：workspace-created → 智能体事件
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 确认下单（冻结 PRD 快照入单）
         * @description 纯按钮零输入：读当前 PRD 全文冻结为订单快照（此后 PRD 修订不影响本单，取消再下 = 新单新快照），待报价起步。下单即冻结迭代——对话区停止受理意见（409 ORD_006），取消订单即解冻回迭代。同项目至多一张未终结订单（重复下单 409 ORD_003，库侧唯一索引兜底）。金额随后台报价落（#29）。项目不存在 404 PRJ_001；PRD 从未产出 409 PRJ_015；项目已归档 409 ORD_004
         */
        post: operations["place"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 改名（需求端右栏「项目信息」inline 改名）
         * @description 名称后改的显式动作（占位名/生成名/已具名均可改，含已归档项目）。响应与详情端点同构——前端改名成功后 invalidate projects 域刷新列表/顶栏。空白拒绝 400 PRJ_005（与建项目同口径），长度上限 100 超限 400；单账号场景不设越权面、不发射 SSE（REST 响应即触达）
         */
        post: operations["rename"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/questions/{qid}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 问答卡作答（ask_user 挂起续跑）
         * @description qid = 挂起事件 engineRef（续跑批复的锚）。请求体回传挂起轮 runId 与待确认工具清单（question-raised 事件 data.toolCalls 原样）+ 用户答复文本（单选 label / 多选拼接 / 自由输入，可与已勾选合并）。续跑续在同一 run 上收口，过程事件经 SSE；恢复私货（会话/配置/工作区）从项目侧事实重建。空白答复 400；已归档 409 PRJ_013；订单处理中 409 ORD_006；项目不存在 404 PRJ_001
         */
        post: operations["answerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/permissions/{ref}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 权限确认卡作答（run 内需批准操作的批准/拒绝续跑，#83 与问答作答分家）
         * @description ref = 挂起事件 engineRef（续跑批复的锚），请求体只携带批准位 + 挂起轮 runId（串卡校验）——恢复私货不回传（挂起事实在平台侧）。批准即放行执行；拒绝即引擎写「用户已拒绝」工具结果回模型，run 据此改道或如实收口（可能仍收口成功）。作答受理即发 permission-resolved 事件（确认卡转已批/已拒），续跑过程事件经 SSE。runId 不符或确认已失效（运行已收口/平台重启丢账）409 PRJ_027（刷新查看最新状态）；项目不存在 404 PRJ_001
         */
        post: operations["answerPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 对话区发言（入口三分类派发：意见/咨询/兜底）
         * @description content 即用户在对话区输入的这句话。平台先经智能体边界上的轻量分类调用三分类（分类失败/超时兜底按意见处理），再按类派发——意见与咨询同一主智能体单会话（main-{projectId}）连续：意见 → 主智能体意见轮消化（追问/改 PRD，轮收口后平台自动派修正 run）；咨询 → 主智能体答询轮（只读工具集查证后直接作答，零产物：PRD 与系统都不动、不起修正 run）；兜底（含下单意图）→ 平台定型轻引导（guide-reply 事件直达对话区，零产物，下单意图指引「确认下单」入口）。对用户全程隐式，无需标注类型。守卫与分类同步完成后返回，runId = 所派运行的标识（意见 = 意见轮 / 咨询 = 答询轮 / 兜底 = guide-reply 事件锚，挂 /api/events?runId= ），回复经 SSE 到达（run-start 事件携带智能体配置键 agent=main）。空白 400；已归档 409 PRJ_013（对话区关闭——咨询与兜底同拦）；订单处理中 409 ORD_006（下单即冻结迭代，取消订单即解冻）仅意见类输入触发；挂起问答待答时：意见 409 PRJ_024（指路作答）、咨询转作答复续跑（与作答通道同路——同挂起 run、咨询文本即答复文本；仅平台重启丢锚的边角 409 PRJ_024 指路作答）、兜底照常引导；项目不存在 404 PRJ_001
         */
        post: operations["postMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重新发起首次生成（失败兜底）
         * @description 生成无门自动发起（#101）后，主智能体产出 PRD 即平台自动派首次生成 run，本端点退为失败兜底——run-failed 后项目仍「未生成」，系统面板「重新发起」重发此端点再触发。纯动作无门——PRD 已产出即可发起（待定项未清也可）。平台先把工作区布局资产就位（AGENTS.md 平台约定幂等覆写），随后下发 run 执行体（coder-{projectId} 会话，AgentScope 单栈，读 docs/PRD.md 在沙箱实现系统并起 8081 端口服务）。异步提交即返回，runId = 首试运行标识（挂 /api/events?runId= 的锚），过程事件经 SSE（run-start agent=executor 起工作消息）。失败自动静默重试有限次（app.generation.max-attempts，默认 3 次含首试，中间失败不出用户面事件），超限转终态发 run-failed 收口事件（前端「重新发起」出口只认本事件——run 失败为唯一失败终态）、由用户重新发起兜底。run 成功收口落 generated_at（首次生成时点，单向置位）。已归档 409 PRJ_013；已生成或生成在途 409 PRJ_017；PRD 从未产出 409 PRJ_018（生成无门后前端无入口，本守卫拦直连调用）；项目不存在 404 PRJ_001
         */
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/fix-runs/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重新修改（修正 run 超限终态恢复出口）
         * @description 修正 run 失败自动重试超限转终态后的人工兜底（与生成的「重新发起」对齐）：重派终态那场的修正任务——交接物沿用（同任务清单）、续同 coder-{projectId} 会话（建系统上下文保留），新 runId = 重派首试标识（挂 /api/events?runId= 的锚，恢复动作与新 run 的链路关系），重派事实落服务端日志可追溯。仅终态可达——正常流程全自动无手动触发：修正在途（进行中/排队中）409 PRJ_025；无终态账（未派过修正/已成功收工/平台重启丢账）409 PRJ_026（指路对话区重提意见）。已归档 409 PRJ_013；系统从未生成 409 PRJ_019；项目不存在 404 PRJ_001
         */
        post: operations["restartFix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 归档（单向终点）
         * @description 落 archived_at：归档是真实动作，重复归档 409 PRJ_013。归档不清工作区
         */
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * mock 支付（确认后同步成功，订单与项目一并归档）
         * @description v1 平台内模拟支付，只走成功路径（真实渠道接入归 PaymentPort 切换边界，#32）。支付成功在一个事务内完成：订单 已支付→已归档（paidAt/archivedAt/paymentNo 落值）+ 项目归档（ADR-0002）；提交后知识沉淀（取归档时最新 PRD 入知识库，失败降级不影响支付）+ 订单态变化 SSE 通知。归档后界面转只读终态（对话区关闭、源码包可取、完整记录含改价历史）。仅已报价（=待支付）态可支付；非待支付 409 ORD_011；订单不存在 404 ORD_001；项目已被手动归档 409 PRJ_013（事务回滚，订单留待支付态）
         */
        post: operations["pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消订单（未支付态，取消即解冻回迭代）
         * @description 自待报价/已报价可达：取消后项目回迭代态（对话区恢复受理意见），同项目可再下新单（新单重新冻结下单时快照）。已支付或已终结 409 ORD_005；订单不存在 404 ORD_001
         */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backoffice/orders/{id}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交报价（已报价态重复提交 = 改价）
         * @description 待报价态首次提交 = 报价（→已报价）；已报价态重复提交 = 改价（状态不变，append-only 价目行留痕、订单现值取最新行，改价历史用户面可见）。限未支付态：已支付/已终结 409 ORD_007；金额非正 400 ORD_008；备注超长 400 ORD_009。需要机机签名
         *
         *     错误码：
         *     - 404 ORD_001 — 订单不存在
         *     - 409 ORD_007 — 订单已支付或已终结，无法报价或改价
         *     - 400 ORD_008 — 报价金额无效（须为正整数，单位分）
         *     - 400 ORD_009 — 报价备注超长（至多 1000 字）
         */
        post: operations["quote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 登录发起
         * @description 种 oauth_txn 事务 cookie（state:nonce:returnTo，600s）并 302 到 identity
         *     /authorize。returnTo 只接受单个 / 开头的同源相对路径（#32，非法回落 /），
         *     登录成功后回跳该路径。
         */
        get: operations["login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 授权码回调
         * @description identity 302 落点（经前端 3333 同源代理）。state 与事务 cookie 精确比对 →
         *     换 token（含 JWKS RS256 验签 + iss/aud/exp/nonce）→ 账号 upsert → 种
         *     aiplatform_session 并 302 回 returnTo。失败 302 回 /?error=state_mismatch
         *     或 /?error=exchange_failed（identity 拒绝授权只带 error 不带 code 时同走
         *     exchange_failed；具体原因只进服务端日志）。
         */
        get: operations["callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询工作区
         * @description 记录 + 资源清单 + 置备状态/失败原因。服务重启后可查（重启接回的验证面）。
         */
        get: operations["get"];
        put?: never;
        post?: never;
        /**
         * 销毁工作区
         * @description 级联清理：容器 → 卷（pg 数据在卷内）→ 库记录。
         */
        delete: operations["destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目详情
         * @description status = 派生项目状态（Integer code：1=进行中 3=已归档，归档优先）
         */
        get: operations["get_1"];
        put?: never;
        post?: never;
        /**
         * 删除项目（真删级联）
         * @description 容器/卷级联清理 + wsp_*\/prj_* 库记录删除；SSE workspace-destroyed
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目用量（总量 + 平台成本 + 分模型 + 分智能体）
         * @description 经计量查询端口按 subject=projectId 聚合。cost 为平台成本口径（token × 事件时点生效单价的机械乘法，币种分桶不折算，无加价/售价）；unpriced 标注有用量但未配单价的档位（其分量不含于 cost，不伪装 0）；byAgentKind 按 dims.agentKind 聚合
         */
        get: operations["usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/source-package": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 源码包下载（常开）
         * @description 交付物 = 源码包 + 仓内文档：打包项目 dev 工作区为 tar.gz（排除 .env 机密与 node_modules）。响应为二进制文件流（application/gzip，本端点不走 ApiResponse JSON 信封）
         */
        get: operations["sourcePackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 预览（工作区端口暴露）
         * @description 端口映射置备时已落定、URL 确定；本端点探活工作区应用端口（run 执行体按约定自起 8081 服务，#44/#45），探活通过才返回可访问 URL（localhost）并SSE preview-ready——前端以此作「应用可访问」判据，通过瞬间切真页面。应用未起服 = 503 WSP_012 待期（非故障），前端 run 开始即轮询续探；平台不代起静态兜底服务，无应用期间不出文件列表中间态
         */
        get: operations["preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/prd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * PRD 读（当前版 markdown，直读工作区）
         * @description PRD = 项目 dev 工作区的 docs/PRD.md（事实源，主智能体的 savePrd 写出，v1 无版本链只最新版）——本端点直读工作区文件返回 {projectId, content, updatedAt}，updatedAt = 文件 mtime（ISO-8601，秒精度）。未产出（工作区无该文件）404 PRJ_015，与项目不存在的 PRJ_001 区分，前端据此呈现「还没产出」。写出/更新时通知通道（/api/events?projectId=）发 document-updated（payload {projectId, documentType:"PRD"}），消费姿势 = invalidate 文档域后重拉本端点
         */
        get: operations["prd"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 项目文件树（交付文件只读浏览）
         * @description 交付文件视图 = 项目 dev 工作区剔除非交付物（data/、.platform/、node_modules/ 与 .env——与源码包同口径）后的文件清单：[{path, size}]，path 为工作区相对路径、按路径稳定排序，只列文件（目录由前端按路径段合成）。直读工作区实时状态——生成/修正 run 完成后即反映最新文件长出。项目不存在 404 PRJ_001
         */
        get: operations["files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 文本文件内容（文件模式点看）
         * @description path = 工作区相对路径（文件树条目原样回传）。只收文本且限大小：非交付物/机密/逃逸路径 400 PRJ_020（判定层拒绝，工作区不被触达）；文件不存在 404 PRJ_021；超过在线查看上限（1 MiB，容器侧拦截不读取）400 PRJ_022；非文本（正文含 NUL）400 PRJ_023。项目不存在 404 PRJ_001
         */
        get: operations["fileContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 对话史（对话面全量，#89 前端水合源）
         * @description 对话面全量落库的读口：用户发言 / 智能体回复 / 问答卡 / 问答作答 / 收尾卡 / 平台轻引导，按写入序（id 升序 = 对话序）全量返回；过程明细（解说段 / 动作卡流水）不在其中（收尾卡已是凝聚物）。kind 小写名分岔；question = question-raised 事件载荷原样（answered=false 即挂起待答——刷新后问答卡可重建可作答）；closing = run-finish 收口扩载同载荷（#88 权威事实，版本锚定 #91 复用）。归档项目照读（对话区只读终态）；项目不存在 404 PRJ_001
         */
        get: operations["conversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订单详情（用户面）
         * @description 状态（Integer code：1=待报价 2=已报价 3=已支付 4=已归档 5=已取消）+ 报价面（总价/币种/后台备注/改价历史新→旧，#29）+ 下单/取消时点+ 支付/归档时点（#30——已支付为瞬态，paidAt 与 archivedAt 同拍）。订单不存在 404 ORD_001
         */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前登录账号
         * @description 凭 aiplatform_session 会话返回 accountId + displayName；无会话 401（统一信封）。
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订阅事件流（SSE，单端点单流）
         * @description 一条流承载两族事件（合并通道不合并语义）：
         *
         *     - 平台通知族（状态变化广播）：只作实时呈现、状态以 REST 重查为准，永不补发；
         *     - 智能体事件族（运行过程流）：带近期事件缓冲的热流——断线重连（浏览器自动
         *       携带非空 Last-Event-ID）先补发缓冲中锚事件之后命中订阅过滤的事件（断线
         *       窗口；锚已被逐出或随重启丢失则补发整段缓冲——缓冲内事件必然晚于锚），
         *       再无缝进实时流；新连接（Last-Event-ID 缺席或空串——含刷新/回访）不补发，
         *       对话史经 REST 水合（GET /api/projects/{id}/conversation，#89），平台状态
         *       以查询收敛。缓冲为单实例内存态（重启即失，多实例化时需重估）。
         *
         *     信封：SSE name 恒为 `event`；id = `{streamId}:{seq}`（通知 streamId=projectId、
         *     智能体事件 streamId=runId）；data = `{"type","payload","ts"}`（payload 恒为
         *     对象、内禁 type 键名）。心跳：每 15s 发注释行 `:ping`。
         *
         *     订阅：`?projectId=` / `?runId=` 过滤（与 payload 关联字段同名，可叠用 AND）；
         *     缺省 = 只收平台通知族（智能体事件族只投递给带过滤的订阅——过程细节是项目
         *     内事实）。智能体事件带 projectId（编排桥接注入）。
         *
         *     名册（type → 说明，payload 除关联字段外）：
         *
         *     | type | 族 | payload 字段 |
         *     |---|---|---|
         *     | workspace-created / preview-ready / preview-updated / workspace-destroyed / document-updated / project-renamed / order-status-changed | 通知 | projectId（+ 各自载荷） |
         *     | run-start | 智能体·生命周期 | runId, prompt, model, engine, agent（可空——main/executor 配置键） |
         *     | error | 智能体·生命周期 | runId, message |
         *     | run-finish | 智能体·生命周期 | runId, sessionId, engine, finish, closing（可缺省——#88 收口扩载：编码 run 真收口携带收尾卡权威事实（summary/prdChanged/systemChanged/files/durationMs），主智能体对话轮不携带） |
         *     | question-raised | 智能体·生命周期 | runId, sessionId, kind, summary, engineRef, data（问答卡投影与待确认工具清单） |
         *     | run-failed / guide-reply | 智能体·生命周期 | runId（+ guide-reply 的 prompt/label/text） |
         *     | acceptance-start | 智能体·生命周期 | runId（#87 受理动作卡：受理轮开场受理事实；落定由该轮 run-finish / error 推导） |
         *     | part-text | 智能体·部件 | text（完整段非增量——消息部件契约） |
         *     | part-action | 智能体·部件 | toolCallId, toolName, state（started/running/completed/failed）, label |
         *     | part-step | 智能体·部件 | step（1 起序号） |
         *     | text / reasoning / patch / tool / step-start / step-finish | 引擎透传 | … + `data`（引擎 part 原样） |
         *
         *     名册正本与字段细则：docs/spec/SSE事件清单.md（新增顶层 type 先进清单再上线）。
         */
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backoffice/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订单清单（按状态过滤，分页）
         * @description 报价工作清单：新单在前（TSID 倒序）。page 1 基（缺省 1）、size 缺省 20（上界 100）；status 可选（Integer code：1=待报价 2=已报价 3=已支付 4=已归档 5=已取消），缺省拉全量。需要机机签名（五头 HMAC），无签名 401
         *
         *     错误码：
         *     - 400 ORD_010 — 无效的订单状态过滤参数
         */
        get: operations["orders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backoffice/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订单详情（后台面）
         * @description 报价依据全量：状态、金额+最新备注、PRD 快照正文（下单冻结）、项目名、下单用户昵称、状态时点组。需要机机签名；订单不存在 404 ORD_001
         *
         *     错误码：
         *     - 404 ORD_001 — 订单不存在
         */
        get: operations["detail_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backoffice/orders/{id}/source-package": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订单源码包（tar.gz 二进制流）
         * @description 交付取件：经项目工作区实时打包（排除 node_modules/.env/data/.platform），不占订单快照。需要机机签名；订单不存在 404 ORD_001；打包失败 500 WSP_002
         *
         *     错误码：
         *     - 404 ORD_001 — 订单不存在
         *     - 500 WSP_002 — 环境后端操作失败
         */
        get: operations["sourcePackage_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 账号清单
         * @description 全量账号（建档顺序、不分页）。accountId 为 TSID 十进制字符串
         */
        get: operations["accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateWorkspaceCommand: {
            /** @description 1=开发, 2=测试, 3=生产 */
            kind?: number;
        };
        ApiResponseWorkspaceResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["WorkspaceResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            field?: string;
            message?: string;
            errorCode?: string;
        };
        MiddlewareResourceResponse: {
            /** @description 1=PostgreSQL, 2=Redis */
            kind?: number;
            kindName?: string;
            containerName?: string;
            /** Format: int32 */
            hostPort?: number;
            url?: string;
        };
        WorkspaceResponse: {
            workspaceId?: string;
            /** @description 1=开发, 2=测试, 3=生产 */
            kind?: number;
            kindName?: string;
            containerName?: string;
            networkName?: string;
            /** Format: int32 */
            previewPort?: number;
            /** @description 1=置备中, 2=就绪, 3=失败 */
            status?: number;
            statusName?: string;
            provisionError?: string;
            resources?: components["schemas"]["MiddlewareResourceResponse"][];
            /** Format: date-time */
            createdAt?: string;
        };
        WorkspaceExecCommand: {
            command: string;
        };
        ApiResponseExecResultResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ExecResultResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ExecResultResponse: {
            stdout?: string;
            stderr?: string;
            /** Format: int32 */
            exitCode?: number;
        };
        CreateProjectCommand: {
            requirement?: string;
        };
        ApiResponseProjectCreatedResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectCreatedResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        OrderBriefResponse: {
            id?: string;
            /** @description 1=待报价, 2=已报价, 3=已支付, 4=已归档, 5=已取消 */
            status?: number;
            statusName?: string;
        };
        ProjectCreatedResponse: {
            project?: components["schemas"]["ProjectDetailResponse"];
            runId?: string;
        };
        ProjectDetailResponse: {
            id?: string;
            name?: string;
            /** @description 1=官网, 2=电商 */
            type?: number;
            typeName?: string;
            workspaceId?: string;
            /** @description 1=进行中, 3=已归档 */
            status?: number;
            statusName?: string;
            archived?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            prdProducedAt?: string;
            /** Format: date-time */
            generatedAt?: string;
            activeOrder?: components["schemas"]["OrderBriefResponse"];
            latestOrder?: components["schemas"]["OrderBriefResponse"];
        };
        ApiResponseOrderResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["OrderResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        OrderResponse: {
            id?: string;
            projectId?: string;
            /** @description 1=待报价, 2=已报价, 3=已支付, 4=已归档, 5=已取消 */
            status?: number;
            statusName?: string;
            /** Format: int64 */
            amount?: number;
            currency?: string;
            note?: string;
            /** Format: date-time */
            quotedAt?: string;
            priceEntries?: components["schemas"]["PriceEntryResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            cancelledAt?: string;
            /** Format: date-time */
            paidAt?: string;
            /** Format: date-time */
            archivedAt?: string;
        };
        PriceEntryResponse: {
            id?: string;
            /** Format: int64 */
            amount?: number;
            currency?: string;
            note?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        RenameProjectCommand: {
            /** @description 新项目名（空白拒绝 PRJ_005，长度上限 100 与建项目同口径） */
            name: string;
        };
        ApiResponseProjectDetailResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectDetailResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        AnswerQuestionCommand: {
            runId: string;
            toolCalls: components["schemas"]["ToolCall"][];
            answer: string;
        };
        ToolCall: {
            id?: string;
            name?: string;
            input?: {
                [key: string]: Record<string, never>;
            };
        };
        ApiResponseVoid: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: Record<string, never>;
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        PermissionAnswerCommand: {
            runId: string;
            approved: boolean;
        };
        PostMessageCommand: {
            content: string;
        };
        ApiResponseInterviewTurnResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["InterviewTurnResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        InterviewTurnResponse: {
            runId?: string;
        };
        ApiResponseGenerationStartResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["GenerationStartResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        GenerationStartResponse: {
            runId?: string;
        };
        ApiResponseFixRestartResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["FixRestartResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        FixRestartResponse: {
            runId?: string;
        };
        SubmitQuoteCommand: {
            /** Format: int64 */
            amount?: number;
            note?: string;
        };
        ApiResponseListProjectResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ProjectResponse: {
            id?: string;
            name?: string;
            /** @description 1=官网, 2=电商 */
            type?: number;
            typeName?: string;
            workspaceId?: string;
            /** @description 1=进行中, 3=已归档 */
            status?: number;
            statusName?: string;
            archived?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            activeOrder?: components["schemas"]["OrderBriefResponse"];
        };
        AgentKindUsage: {
            agentKind?: string;
            agentKindLabel?: string;
            tokens?: components["schemas"]["TokenUsage"];
        };
        ApiResponseProjectUsageResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectUsageResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ModelUsage: {
            provider?: string;
            model?: string;
            tokens?: components["schemas"]["TokenUsage"];
        };
        ProjectUsageResponse: {
            projectId?: string;
            total?: components["schemas"]["TokenUsage"];
            cost?: {
                [key: string]: number;
            };
            unpriced?: components["schemas"]["UnpricedUsage"][];
            byModel?: components["schemas"]["ModelUsage"][];
            byAgentKind?: components["schemas"]["AgentKindUsage"][];
        };
        TokenUsage: {
            /** Format: int64 */
            input?: number;
            /** Format: int64 */
            output?: number;
            /** Format: int64 */
            cacheRead?: number;
            /** Format: int64 */
            cacheWrite?: number;
            /** Format: int64 */
            reasoning?: number;
        };
        UnpricedUsage: {
            provider?: string;
            model?: string;
            /** @description 1=输入, 2=输出, 3=缓存读, 4=缓存写, 5=推理 */
            tokenKind?: number;
            tokenKindName?: string;
        };
        ApiResponseProjectPreviewResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectPreviewResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ProjectPreviewResponse: {
            url?: string;
        };
        ApiResponsePrdResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PrdResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        PrdResponse: {
            projectId?: string;
            content?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseProjectFilesResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectFilesResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        FileEntry: {
            path?: string;
            /** Format: int64 */
            size?: number;
        };
        ProjectFilesResponse: {
            projectId?: string;
            files?: components["schemas"]["FileEntry"][];
        };
        ApiResponseProjectFileContentResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ProjectFileContentResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ProjectFileContentResponse: {
            path?: string;
            content?: string;
        };
        ApiResponseListConversationEntryResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["ConversationEntryResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        ConversationEntryResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            kind?: number;
            runId?: string;
            text?: string;
            question?: {
                [key: string]: Record<string, never>;
            };
            closing?: {
                [key: string]: Record<string, never>;
            };
            attachments?: {
                [key: string]: Record<string, never>;
            }[];
            answered?: boolean;
            /** Format: date-time */
            at?: string;
        };
        ApiResponseMeResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["MeResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        /** @description 当前登录账号 */
        MeResponse: {
            /**
             * @description 账号 id（内部 TSID，字符串承载——超出 JS 安全整数范围）
             * @example 3897654321098765432
             */
            accountId?: string;
            /**
             * @description 显示名（nickname→name→preferred_username→sub 推导）
             * @example 张三
             */
            displayName?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        ApiResponsePageResponseBackofficeOrderSummaryResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["PageResponseBackofficeOrderSummaryResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        BackofficeOrderSummaryResponse: {
            id?: string;
            projectId?: string;
            projectName?: string;
            /** @description 1=待报价, 2=已报价, 3=已支付, 4=已归档, 5=已取消 */
            status?: number;
            statusName?: string;
            /** Format: int64 */
            amount?: number;
            currency?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            quotedAt?: string;
        };
        PageResponseBackofficeOrderSummaryResponse: {
            items?: components["schemas"]["BackofficeOrderSummaryResponse"][];
            /** Format: int64 */
            total?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        ApiResponseBackofficeOrderDetailResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["BackofficeOrderDetailResponse"];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        BackofficeOrderDetailResponse: {
            id?: string;
            projectId?: string;
            projectName?: string;
            ownerDisplayName?: string;
            /** @description 1=待报价, 2=已报价, 3=已支付, 4=已归档, 5=已取消 */
            status?: number;
            statusName?: string;
            /** Format: int64 */
            amount?: number;
            currency?: string;
            note?: string;
            prdSnapshot?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            quotedAt?: string;
            /** Format: date-time */
            paidAt?: string;
            /** Format: date-time */
            archivedAt?: string;
            /** Format: date-time */
            cancelledAt?: string;
        };
        AccountResponse: {
            accountId?: string;
            displayName?: string;
        };
        ApiResponseListAccountResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AccountResponse"][];
            requestId?: string;
            errors?: components["schemas"]["FieldError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                aiplatform_session?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWorkspaceResponse"];
                };
            };
        };
    };
    retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWorkspaceResponse"];
                };
            };
        };
    };
    exec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceExecCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExecResultResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                status?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListProjectResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectCreatedResponse"];
                };
            };
        };
    };
    place: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponse"];
                };
            };
        };
    };
    rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameProjectCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    answerQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                qid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerQuestionCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    answerPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionAnswerCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    postMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostMessageCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInterviewTurnResponse"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGenerationStartResponse"];
                };
            };
        };
    };
    restartFix: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFixRestartResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    pay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponse"];
                };
            };
        };
    };
    quote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitQuoteCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: {
                /** @description 登录后回跳路径（同源相对路径，非法回落 /） */
                returnTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    callback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                oauth_txn?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id（TSID 字符串） */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWorkspaceResponse"];
                };
            };
        };
    };
    destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作区 id */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    usage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectUsageResponse"];
                };
            };
        };
    };
    sourcePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectPreviewResponse"];
                };
            };
        };
    };
    prd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePrdResponse"];
                };
            };
        };
    };
    files: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectFilesResponse"];
                };
            };
        };
    };
    fileContent: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectFileContentResponse"];
                };
            };
        };
    };
    conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListConversationEntryResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMeResponse"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: {
                /** @description 按项目过滤（与信封关联字段同名；缺省只收通知族） */
                projectId?: string;
                /** @description 按运行过滤（智能体事件族的「看某个运行才挂」姿势；缺省不过滤） */
                runId?: string;
            };
            header?: {
                /** @description SSE 断线重连自动携带；有值 = 重连 = 补发锚事件之后的缓冲窗口（断线补发），无值 = 新连接 = 不补发（对话史经 REST 水合，平台状态以查询收敛） */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    orders: {
        parameters: {
            query?: {
                status?: number;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseBackofficeOrderSummaryResponse"];
                };
            };
        };
    };
    detail_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBackofficeOrderDetailResponse"];
                };
            };
        };
    };
    sourcePackage_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    accounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAccountResponse"];
                };
            };
        };
    };
}
